### PR TITLE
feature/preview window

### PR DESCRIPTION
**Pull request by dkirchhof**
- feat: show preview in a separate window
- docs: added docs for the client-parent-communication (ready event)
- docs: added changelog entry; bump version;

### CODE REVIEW

**Comment by dkirchhof** [comment]
@jpeiniger what do you think? Right now, there is a button above the iframe to open the preview in a separate window. It will automatically close the iframe.

Should we add an option to show the preview 
1. always in an iframe
2. always in a window
3. allow both (like I've implemented it)

We could also save the preview type in the localStorage to remember the preference.


We should also mention the new preview window somewhere in the docs.


Is the "backport" part okay? Could be a first preparation for some more functions like "click somewhere in the frontend and set the focus in the backend".

**Comment by dkirchhof** [comment]
I'm trying to implement some new features which will lead to breaking changes again. So if you're happy with the pr, wait for merging :grin:

**Comment by jpeiniger** [comment]
Works like a charm on the first glimpse. 

One thing: When leaving the edit view in den admin UI, we should probably close the preview window (if open). Because otherweise, when I then navigate to another edit view. e.g. from the example "KitchenSink" to the "Post" collection, the old preview window stays open and the new preview is shown in the main admin UI window.

Bildschirmfoto 2023-08-05 um 12 10 00

**Comment by dkirchhof** [comment]
To close the window would probably be the simplest solution. We could also change the preview. But then we have to check, if you navigate to a page where the preview is enabled.

**Pull request closed without merging**
